services:
  - type: web
    name: neural-trajectory-dashboard
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python neural_trajectory_dashboard.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: PORT
        value: 8050 